version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports: 
      - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./data/prometheus:/etc/prometheus 
    - ./data/prometheus/data:/prometheus
    depends_on:
    - node
    - consul1
    - consul2
    - consul3 
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports: 
      - 3000:3000
    depends_on:
    - prometheus 
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    #ports: 
    #  - 9093:9093
    network_mode: host
    volumes: 
      - ./data/alertmanager:/etc/alertmanager
      - ./data/alertmanager/storage:/alertmanager
  node:
     image: prom/node-exporter:latest
     restart: always
     container_name: node-exporter
     ports: 
      - 9100:9100
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
    - 6379:6379
  consul1:
    image: consul
    container_name: node1
    volumes: 
      - ./consul/config:/consul/config
    command: agent -server -bootstrap-expect=2 -node=node1 -bind=0.0.0.0 -client=0.0.0.0 -config-dir=/consul/config
  consul2:
    image: consul
    container_name: node2
    volumes:
      - ./consul/config:/consul/config
    command: agent -server -retry-join=node1 -node=node2 -bind=0.0.0.0 -client=0.0.0.0 -config-dir=/consul/config
    ports:
       - 8500:8500
    depends_on:
        - consul1
  consul3:
    image: consul
    volumes:
      - ./consul/config:/consul/config
    container_name: node3
    command: agent -server -retry-join=node1 -node=node3 -bind=0.0.0.0 -client=0.0.0.0 -config-dir=/consul/config
    depends_on:
        - consul1
  exporter:
     image: prom/node-exporter:latest
     restart: always
     container_name: node-exporter1
     ports: 
      - 9101:9100
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql80
    environment:
      MYSQL_ROOT_PASSWORD: togerme
      MYSQL_DATABASE: test
      MYSQL_USER: hbu
      MYSQL_PASSWORD: togerme
    ports:
      - "3307:3306"
  mysqld-exporter:
    depends_on:
      - mysql
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter 
    ports:
      - "9104:9104"
    #network_mode: "container:mysql80"
    environment:
      DATA_SOURCE_NAME: hbu:togerme@(mysql80:3306)/