---
- include: redhat.yml
  when: ansible_os_family == "RedHat"
  
- include: ubuntu.yml
  when: ansible_os_family == "Debian"
  
- name: Download Nginx
  get_url: url={{ download_url }} dest={{ download_dir }}

- name: Extract Nginx
  unarchive: src={{ download_dir }}/nginx-{{nginx_version}}.tar.gz dest={{challenge_dir}}


- name: Copy Nginx Install Shell Script
  template: src=configure.sh dest={{challenge_dir}}/nginx-{{nginx_version}} mode="u=rwx,g=rw,o=r"

- name: Configure Nginx
  command: /bin/bash /{{challenge_dir}}/nginx-{{nginx_version}}/configure.sh

- name: Install nginx
  shell: cd {{challenge_dir}}/nginx-{{nginx_version}}/ && make && make install
